### ISSUE TITLE
ReferenceError: log is not defined

### ISSUE THREAD

**Issue by brazabr** [klassijs/klassi-js#15]
I cloned your repo and ran the default test. Without doing anything I had the following error:

```(node:1394) UnhandledPromiseRejectionWarning: ReferenceError: log is not defined
    at /mnt/c/Users/braza/Code/klassi-cucumber-js/index.js:216:5
    at new Promise (<anonymous>)
    at Object.<anonymous> (/mnt/c/Users/braza/Code/klassi-cucumber-js/index.js:200:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
(node:1394) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1394) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```
```

I managed to change to this error to the one reported in #14 after `npm i log` and add these two lines in index.js:
```js
const Log = require('log'),
      log = new Log('info');
```

**Comment by larryg01** [comment]
that was an oversight 
log = require('./runtime/logger')

replace your two lines above with that line and uninstall 'log'
