### ISSUE TITLE
Cannot resolve ./runtime/envConfig

### ISSUE THREAD

**Issue by wolasss** [klassijs/klassi-js#52]
If I run 

`node ./node_modules/klassi-js/index.js -s [path to my step definitions]` 

I get: 

```module.js:550
    throw err;
    ^

Error: Cannot find module './runtime/envConfig'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/wolas/sensotransel/sensotransel-vision/node_modules/klassi-js/index.js:51:17)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3```

By the way - why klassi-js is not registered as an executable as any other npm package so I can use it as:

`klassi-js -s [path]` in my npm package.json scripts ?

**Comment by larryg01** [comment]
Hi wolass,

Thanks for the spot, I have updated the command as it should read " node ./index.js -ds ./step_definitions "

As for your question I am not following can you give me an example of what you are trying to say please
